### ISSUE TITLE
Cannot move <resource_id_created_with_for_each> does not match anything in the current state.

### ISSUE THREAD

**Issue by m0ps** [shebang-labs/terraform-state-split#2]
I'm trying to split tf state, which consists of a lot of resources created with `for_each`, and it fails with the following error. 
```
│ Error: Invalid source address
│
│ Cannot move module.s3_bucket["bucket1"].aws_s3_bucket_policy.this: does not
│ match anything in the current state.
```

**Comment by tarek-optibrium** [comment]
I will look into this today and feedback to you 👍

**Comment by tareksamni** [comment]
I will have a look into this today and feedback to you later! Thanks for reporting this issue.
